const { Router } = require('express');
const multer = require('multer');
const { protect, authorize } = require('../middleware/authMiddleware');
const c = require('../controllers/contractController');
const router = Router();
const upload = multer({ dest: '/tmp/uploads/' });
router.use(protect);
router.route('/').get(c.listContracts);
router.post('/upload', authorize('contract_manager', 'pmo'), upload.single('file'), c.uploadContract);
router.route('/:id').get(c.getContract).put(authorize('contract_manager', 'pmo'), c.updateContract);
router.post('/:id/analyze', authorize('contract_manager', 'pmo'), c.reanalyzeContract);
router.get('/:id/timeline', c.getTimeline);
module.exports = router;
