const { Router } = require('express');
const { protect, authorize } = require('../middleware/authMiddleware');
const c = require('../controllers/financeController');
const router = Router();
router.use(protect);
router.route('/planned/:contractId').get(c.getPlannedBudget).put(authorize('pmo'), c.updatePlannedBudget);
router.route('/actual').get(c.listActualReports).post(authorize('finance_team', 'pmo'), c.submitActualReport);
router.put('/actual/:id/approve', authorize('pmo'), c.approveReport);
router.put('/actual/:id/reject', authorize('pmo'), c.rejectReport);
module.exports = router;
